/**
 * Export module for AI Book Generator
 * Handles various export formats and file generation
 */

import { CONFIG } from './config.js';
import { showAlert } from './ui.js';

class ExportManager {
    constructor() {
        this.bookData = null;
    }

    setBookData(data) {
        this.bookData = data;
    }

    // Text export
    exportAsText() {
        if (!this.bookData) {
            showAlert('No book data to export', 'error');
            return;
        }

        const textContent = this.generateTextContent();
        this.downloadFile(textContent, 'book.txt', CONFIG.EXPORT_FORMATS.TXT);
    }

    generateTextContent() {
        let content = '';
        
        // Title
        if (this.bookData.title) {
            content += `${this.bookData.title}\n`;
            content += '='.repeat(this.bookData.title.length) + '\n\n';
        }
        
        // Concept
        if (this.bookData.concept) {
            content += 'CONCEPT\n';
            content += '-------\n';
            content += this.bookData.concept + '\n\n';
        }
        
        // Table of Contents
        if (this.bookData.tableOfContents) {
            content += 'TABLE OF CONTENTS\n';
            content += '-----------------\n';
            content += this.bookData.tableOfContents + '\n\n';
        }
        
        // Chapters
        if (this.bookData.chapters && this.bookData.chapters.length > 0) {
            content += 'CHAPTERS\n';
            content += '--------\n\n';
            
            this.bookData.chapters.forEach((chapter, index) => {
                content += `Chapter ${index + 1}: ${chapter.title}\n`;
                content += '-'.repeat(`Chapter ${index + 1}: ${chapter.title}`.length) + '\n';
                content += this.stripHtml(chapter.content) + '\n\n';
            });
        }
        
        // Footer
        content += `\n\nGenerated by AI Book Generator on ${new Date().toLocaleString()}`;
        
        return content;
    }

    // HTML export
    exportAsHtml() {
        if (!this.bookData) {
            showAlert('No book data to export', 'error');
            return;
        }

        const htmlContent = this.generateHtmlContent();
        this.downloadFile(htmlContent, 'book.html', CONFIG.EXPORT_FORMATS.HTML);
    }

    generateHtmlContent() {
        const title = this.bookData.title || 'AI Generated Book';
        
        let html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${this.escapeHtml(title)}</title>
    <style>
        body {
            font-family: 'Georgia', serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }
        .book-title {
            text-align: center;
            font-size: 2.5em;
            margin-bottom: 0.5em;
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 20px;
        }
        .concept {
            background-color: #f8f9fa;
            padding: 20px;
            border-left: 4px solid #3498db;
            margin: 20px 0;
        }
        .table-of-contents {
            background-color: #fff;
            padding: 20px;
            border: 1px solid #ddd;
            margin: 20px 0;
        }
        .chapter {
            margin: 40px 0;
            page-break-before: always;
        }
        .chapter-title {
            color: #2c3e50;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .chapter-content {
            text-align: justify;
        }
        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 0.9em;
        }
        @media print {
            body { margin: 0; }
            .chapter { page-break-before: always; }
        }
    </style>
</head>
<body>`;

        // Title
        html += `    <h1 class="book-title">${this.escapeHtml(title)}</h1>\n`;
        
        // Concept
        if (this.bookData.concept) {
            html += `    <div class="concept">
        <h2>Concept</h2>
        <p>${this.escapeHtml(this.bookData.concept).replace(/\n/g, '</p><p>')}</p>
    </div>\n`;
        }
        
        // Table of Contents
        if (this.bookData.tableOfContents) {
            html += `    <div class="table-of-contents">
        <h2>Table of Contents</h2>
        <pre>${this.escapeHtml(this.bookData.tableOfContents)}</pre>
    </div>\n`;
        }
        
        // Chapters
        if (this.bookData.chapters && this.bookData.chapters.length > 0) {
            this.bookData.chapters.forEach((chapter, index) => {
                html += `    <div class="chapter">
        <h2 class="chapter-title">Chapter ${index + 1}: ${this.escapeHtml(chapter.title)}</h2>
        <div class="chapter-content">${chapter.content}</div>
    </div>\n`;
            });
        }
        
        // Footer
        html += `    <div class="footer">
        Generated by AI Book Generator on ${new Date().toLocaleString()}
    </div>
</body>
</html>`;

        return html;
    }

    // Markdown export
    exportAsMarkdown() {
        if (!this.bookData) {
            showAlert('No book data to export', 'error');
            return;
        }

        const markdownContent = this.generateMarkdownContent();
        this.downloadFile(markdownContent, 'book.md', CONFIG.EXPORT_FORMATS.MARKDOWN);
    }

    generateMarkdownContent() {
        let markdown = '';
        
        // Title
        if (this.bookData.title) {
            markdown += `# ${this.bookData.title}\n\n`;
        }
        
        // Concept
        if (this.bookData.concept) {
            markdown += '## Concept\n\n';
            markdown += this.bookData.concept + '\n\n';
        }
        
        // Table of Contents
        if (this.bookData.tableOfContents) {
            markdown += '## Table of Contents\n\n';
            const tocLines = this.bookData.tableOfContents.split('\n');
            tocLines.forEach((line, index) => {
                if (line.trim()) {
                    markdown += `${index + 1}. ${line.trim()}\n`;
                }
            });
            markdown += '\n';
        }
        
        // Chapters
        if (this.bookData.chapters && this.bookData.chapters.length > 0) {
            this.bookData.chapters.forEach((chapter, index) => {
                markdown += `## Chapter ${index + 1}: ${chapter.title}\n\n`;
                markdown += this.stripHtml(chapter.content) + '\n\n';
                markdown += '---\n\n';
            });
        }
        
        // Footer
        markdown += `*Generated by AI Book Generator on ${new Date().toLocaleString()}*\n`;
        
        return markdown;
    }

    // JSON export
    exportAsJson() {
        if (!this.bookData) {
            showAlert('No book data to export', 'error');
            return;
        }

        const jsonData = {
            ...this.bookData,
            metadata: {
                exportedAt: new Date().toISOString(),
                version: '2.0',
                generator: 'AI Book Generator'
            }
        };

        const jsonContent = JSON.stringify(jsonData, null, 2);
        this.downloadFile(jsonContent, 'book.json', CONFIG.EXPORT_FORMATS.JSON);
    }

    // EPUB export (basic structure)
    exportAsEpub() {
        showAlert('EPUB export coming soon! For now, use HTML export and convert with Calibre.', 'info', true, 10000);
    }

    // PDF export guidance
    exportAsPdf() {
        const htmlContent = this.generateHtmlContent();
        const blob = new Blob([htmlContent], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        
        // Open in new window for printing
        const printWindow = window.open(url, '_blank');
        printWindow.onload = () => {
            showAlert('Use your browser\'s Print function and select "Save as PDF" for PDF export.', 'info', true, 10000);
        };
    }

    // Utility methods
    downloadFile(content, filename, mimeType) {
        try {
            const blob = new Blob([content], { type: mimeType + ';charset=utf-8' });
            const url = URL.createObjectURL(blob);
            
            const link = document.createElement('a');
            link.href = url;
            link.download = filename;
            link.style.display = 'none';
            
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            
            // Clean up
            setTimeout(() => URL.revokeObjectURL(url), 100);
            
            showAlert(`Book exported as ${filename}`, 'success');
        } catch (error) {
            console.error('Export failed:', error);
            showAlert('Export failed. Please try again.', 'error');
        }
    }

    stripHtml(html) {
        const tmp = document.createElement('div');
        tmp.innerHTML = html;
        return tmp.textContent || tmp.innerText || '';
    }

    escapeHtml(text) {
        const div = document.createElement('div');
        div.textContent = text;
        return div.innerHTML;
    }

    // Advanced export options
    exportWithCustomTemplate(template, data) {
        // Future implementation for custom templates
        showAlert('Custom templates coming soon!', 'info');
    }

    // Batch export
    exportAll() {
        if (!this.bookData) {
            showAlert('No book data to export', 'error');
            return;
        }

        // Create a zip file with all formats
        showAlert('Exporting in all formats...', 'info');
        
        setTimeout(() => this.exportAsText(), 100);
        setTimeout(() => this.exportAsHtml(), 200);
        setTimeout(() => this.exportAsMarkdown(), 300);
        setTimeout(() => this.exportAsJson(), 400);
        
        showAlert('All formats exported successfully!', 'success', true, 5000);
    }

    // Get word count
    getWordCount() {
        if (!this.bookData || !this.bookData.chapters) return 0;
        
        return this.bookData.chapters.reduce((total, chapter) => {
            const text = this.stripHtml(chapter.content);
            return total + text.split(/\s+/).filter(word => word.length > 0).length;
        }, 0);
    }

    // Get reading time estimate
    getReadingTime() {
        const wordCount = this.getWordCount();
        const averageWPM = 200; // Average reading speed
        const minutes = Math.ceil(wordCount / averageWPM);
        
        if (minutes < 60) {
            return `${minutes} minutes`;
        } else {
            const hours = Math.floor(minutes / 60);
            const remainingMinutes = minutes % 60;
            return `${hours} hour${hours > 1 ? 's' : ''} ${remainingMinutes} minutes`;
        }
    }

    // Generate book statistics
    getBookStatistics() {
        if (!this.bookData) return null;
        
        const wordCount = this.getWordCount();
        const chapterCount = this.bookData.chapters ? this.bookData.chapters.length : 0;
        const averageChapterLength = chapterCount > 0 ? Math.round(wordCount / chapterCount) : 0;
        
        return {
            wordCount,
            chapterCount,
            averageChapterLength,
            readingTime: this.getReadingTime(),
            characterCount: this.bookData.chapters ? 
                this.bookData.chapters.reduce((total, chapter) => 
                    total + this.stripHtml(chapter.content).length, 0) : 0
        };
    }
}

// Export singleton instance
export const exportManager = new ExportManager();